//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEvent
    {
        public int Id { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public TaskStates TaskState { get; set; }
    
        public virtual DataTask Task { get; set; }
    }
}
