//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProject.Data
{
    using System;
    
    public enum ISTypes : byte
    {
        DirectoryService = 100,
        Mailserver = 101,
        Mailrelay = 102,
        ERP = 103,
        Docflow = 104,
        Fileserver = 105,
        Portal = 106
    }
}
