//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProject.Data
{
    using System;
    
    public enum TaskTypes : byte
    {
        CreateUser = 201,
        DeleteUser = 202,
        DenyAccess = 203,
        PermitAccess = 204,
        BlockUser = 205
    }
}
