//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProject.Data
{
    using System;
    
    public enum TaskStates : byte
    {
        Created = 1,
        InProcessing = 2,
        Completed = 3,
        Terminated = 4
    }
}
